[mgr]
border_symbol = "│"
border_style = { fg = "#555555" }
tab_active = { reversed = true }
tab_inactive = {}
count_copied = { fg = "#a6e3a1", bg = "reset" }
count_cut = { fg = "#f38ba8", bg = "reset" }
count_selected = { fg = "#f9e2af", bg = "reset" }

[indicator]
current = { fg = "brightwhite", bold = true }
padding = { open = "", close = "" }

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }
mode_normal = { bg = "reset", bold = true }
mode_select = { bg = "reset", bold = true }
mode_unset = { bg = "reset", bold = true }

[filetype]
rules = [
  { mime = "*", fg = "brightblack" },
  { url = "*/", fg = "brightblack" },
]
